name: affinity-net
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.10
  - torchvision=0.11
  - cudatoolkit=11.3
  - numpy=1.22
  - pillow=9.0
  - matplotlib=3.5
  - opencv=4.5
  - tqdm=4.62
  - scipy=1.8
  - pip=21.3
  - pip:
    - pydensecrf
    - tensorboardX 